### ISSUE TITLE
react-addons-transition-group deprecated on react 16

### ISSUE THREAD

**Issue by stefensuhat** [LouisBarranqueiro/reapop#41] opened 2017-04-27 01:25 UTC
### Configuration

 - **Operating system with version** :  Windows 10 
 - **Browser with version** :  Latest Chrome
 - **Reapop version** : 1.0.0
 - **React version** : 15.5.3
 - **Redux version** : 3.6.0
 - **React-redux version** : 5.0.4
 
Today when I ran `yarn upgrade` got this at the beginning of installation

`warning reapop > react-addons-css-transition-group@15.5.2: This package is deprecated and will no longer work with React 16+. We recommend you use CSSTransitionGroup from 'react-transition-group' instead.`

Thanks

**Comment by LouisBarranqueiro** [comment] 2017-04-29 20:15
duplicate of #34

**Closed by LouisBarranqueiro** 2017-04-29 20:15 UTC
Labels: bug, duplicate
