### ISSUE TITLE
Require does not work. require('./path/file.css')

### ISSUE THREAD

**Issue by dijimon** [LouisBarranqueiro/reapop#153] opened 2019-06-14 12:10 UTC
I've installed "reapop" in my app. And looks like functionality is working, but styles have not applied. When debugging I found that "var css = require('./lib/styles.css');"  in  "/reapop-theme-wybo/index.js" is not working.

Here is an example of code:
```
'use strict';

var css = require('./lib/styles.css');  // file exists

//!!!!!!!  css = undefined   !!!!!!!!!!!

// media breakpoint - small screen min width
var smallScreenMin = 768;

// default className for NotificationsSystem component
var notificationsSystemClassName = css['notifications-system'];

// default className for NotificationsContainer component
var notificationsContainerClassName = {
  main: css['notifications-container'],
  position: function position(_position) {
    return css['notifications-container--' + _position];
  }
};
```

browser shows me the following warning:
`Warning: Failed prop type: The prop `theme.notificationsContainer.className.main` is marked as required in `NotificationsContainer`, but its value is `undefined`.`

Do you know why it may happens?

**Comment by LouisBarranqueiro** [comment] 2019-06-16 05:23
👋 @dijimon, please follow the template to report a bug if you want me to help you: https://github.com/LouisBarranqueiro/reapop/issues/new?assignees=LouisBarranqueiro&labels=&template=bug_report.md

**Comment by omniait** [comment] 2019-08-08 08:26
I'm having the same problem

### Description
I'm trying to use the reapop default theme (wybo), but the theme is undefined.

### Expected behavior
Import reapop, register the notification system, apply the default wybo theme, call a notification and see it.

![immagine](https://user-images.githubusercontent.com/33842139/62687125-6626e900-b9c6-11e9-84d5-4be435240307.png)

### Steps to reproduce the bug
 Import reapop and wybo theme, try to apply the theme to reapop.

### Environment
 - **Windows 10 1903** : 
 - **Latest Firefox developers edition and Chrome tested**:
 - **2.0.1**:

### Additional information

**Comment by keymastervn** [comment] 2019-08-12 08:44
I made it passed through a watch on the `webpack.config.js` in the demo folder
> https://github.com/LouisBarranqueiro/reapop/blob/master/demo/webpack.config.js

then modified my own webpack config file
```
test: /\.css$/,
  use: [
    {
      loader: 'style-loader' // creates style nodes from JS strings
    },
    {
      loader: 'css-loader',
      options: {
        importLoaders: 1,
        modules: true,
        localIdentName: '[name]__[local]___[hash:base64:5]'
      }
    }
  ]
```
---
css-loader: ^2.1.1
style-loader: ^0.23.1

**Comment by omniait** [comment] 2019-08-12 09:01
Sadly we do have a problem in configuring Webpack with create-react-app; a solution I've found is to copy-paste the theme as SCSS and make it valid, then use that "custom" theme.

**Comment by keymastervn** [comment] 2019-08-13 08:34
@omniait for the zero-configuration webpack@4, it would automatically treat a CSS file as css-modules if they have a naming convention like `\.module\.[a-z]+$` 

I strongly believe `CRA` has a good default config for loading css-modules, as my `@rails/webpacker` does and modifying it is not a good way to go

```js
// console.log defaultConfig
{ key: 'css',
    value:
     { test: /\.(css)$/i,
       use: [Array],
       sideEffects: true,
       exclude: /\.module\.[a-z]+$/ } },
  { key: 'sass',
    value:
     { test: /\.(scss|sass)$/i,
       use: [Array],
       sideEffects: true,
       exclude: /\.module\.[a-z]+$/ } },
  { key: 'moduleCss',
    value:
     { test: /\.(css)$/i,
       use: [Array],
       sideEffects: false,
       include: /\.module\.[a-z]+$/ } },
  { key: 'moduleSass',
    value:
     { test: /\.(scss|sass)$/i,
       use: [Array],
       sideEffects: false,
       include: /\.module\.[a-z]+$/ } }
```

There is a PR for naming update, @LouisBarranqueiro please have a check if this can work with the default webpack4 config, then the recommended config in README should be applicable for webpack3 and below.
https://github.com/LouisBarranqueiro/reapop-theme-wybo/pull/12

**Comment by keymastervn** [comment] 2019-08-13 08:45
I can confirm that changing the filename `styles.css` -> `styles.module.css` can work without any configuration added

----
webpack: ^4.32.2

**Comment by LouisBarranqueiro** [comment] 2019-09-28 22:07
> @omniait for the zero-configuration webpack@4, it would automatically treat a CSS file as css-modules if they have a naming convention like `\.module\.[a-z]+$`
> 
> I strongly believe `CRA` has a good default config for loading css-modules, as my `@rails/webpacker` does and modifying it is not a good way to go
> 
> ```js
> // console.log defaultConfig
> { key: 'css',
>     value:
>      { test: /\.(css)$/i,
>        use: [Array],
>        sideEffects: true,
>        exclude: /\.module\.[a-z]+$/ } },
>   { key: 'sass',
>     value:
>      { test: /\.(scss|sass)$/i,
>        use: [Array],
>        sideEffects: true,
>        exclude: /\.module\.[a-z]+$/ } },
>   { key: 'moduleCss',
>     value:
>      { test: /\.(css)$/i,
>        use: [Array],
>        sideEffects: false,
>        include: /\.module\.[a-z]+$/ } },
>   { key: 'moduleSass',
>     value:
>      { test: /\.(scss|sass)$/i,
>        use: [Array],
>        sideEffects: false,
>        include: /\.module\.[a-z]+$/ } }
> ```
> 
> There is a PR for naming update, @LouisBarranqueiro please have a check if this can work with the default webpack4 config, then the recommended config in README should be applicable for webpack3 and below.
> [LouisBarranqueiro/reapop-theme-wybo#12](https://github.com/LouisBarranqueiro/reapop-theme-wybo/pull/12)

👋 @keymastervn  I will check that out. I'm closing this issue since it's related to the theme and not the library

**Closed by LouisBarranqueiro** 2019-09-28 22:07 UTC
