### ISSUE TITLE
`theme.notificationsContainer.className.main` is marked as required in

### ISSUE THREAD

**Issue by RathanakSreang** [LouisBarranqueiro/reapop#82] opened 2018-09-05 08:00 UTC
How can I fix this error?
```
`theme.notificationsContainer.className.main` is marked as required in `NotificationsContainer`, but its value is `undefined`.
```

**Comment by dubvfan87** [comment] 2018-09-05 19:47
I'm getting this error as well.

**Comment by LouisBarranqueiro** [comment] 2018-10-05 18:08
:wave: @RathanakSreang, Please respect the template to report a bug, otherwise it's hard for me to work on it.

**Comment by LouisBarranqueiro** [comment] 2018-10-11 05:32
I'm closing this one for now, please re-open it when it is updated so I get a notification :)

**Closed by LouisBarranqueiro** 2018-10-11 05:32 UTC

**Comment by kingkyle** [comment] 2019-03-04 13:07
> How can I fix this error?
> 
> ```
> `theme.notificationsContainer.className.main` is marked as required in `NotificationsContainer`, but its value is `undefined`.
> ```

how can i fix this error please?

**Comment by nurbek-ab** [comment] 2019-05-20 17:37
I think @dubvfan87 was pretty close to the cause of the bug. He doesn't use css modules, so do I. This lib looks promising but not very suitable for people having their projects already set up.

**Comment by GektorGrom** [comment] 2019-08-23 05:16
I had this issue when upgrade css-loader to version 3.0.0
here's my updated config if someone have same issue
```
use: ExtractTextPlugin.extract({
          use: [{
            loader: 'css-loader',
            options: {
              modules: 'global',
              importLoaders: 1,
            },
          }, {
            loader: 'postcss-loader',
            options: {
              plugins: () => [
                // eslint-disable-next-line global-require
                require('postcss-smart-import'),
                // eslint-disable-next-line global-require
                require('autoprefixer'),
              ],
            },
          }, {
            loader: 'sass-loader',
          }],
        }),
```
ExtractTextPlugin.extract is optional, issue was with missing options
```
options: {
              modules: 'global',
              importLoaders: 1,
            },
```
